package com.forlks.personal_wellness_routine.data.db.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "diary_entries")
data class DiaryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val date: String,           // "yyyy-MM-dd"
    val content: String,
    val emotionEmoji: String,   // 😊 😐 😔 etc
    val emotionScore: Float,    // -1.0 ~ 1.0
    val emotionLabel: String,   // 긍정/중립/부정
    val tags: String,           // comma-separated "#활력,#운동"
    val isAutoGenerated: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)
