package com.forlks.personal_wellness_routine.domain.model

// ── Routine ──────────────────────────────────────────────────────────────────
enum class RoutineCategory(val label: String) {
    ALL("전체"), HEALTH("건강"), MIND("마음"), STUDY("학습")
}

data class Routine(
    val id: Long = 0,
    val name: String,
    val category: RoutineCategory,
    val emoji: String,
    val scheduledTime: String,
    val durationMinutes: Int,
    val streak: Int = 0,
    val isCompletedToday: Boolean = false
)

// ── Diary ─────────────────────────────────────────────────────────────────────
data class DiaryEntry(
    val id: Long = 0,
    val date: String,
    val content: String,
    val emotionEmoji: String,
    val emotionScore: Float,
    val emotionLabel: String,
    val tags: List<String> = emptyList(),
    val isAutoGenerated: Boolean = false
)

// ── KakaoTalk Analysis ────────────────────────────────────────────────────────
enum class TemperatureLevel(val label: String, val emoji: String, val threshold: Int) {
    COLD("냉랭함", "🥶", 0),
    COOL("차가움", "😶", 35),
    NORMAL("보통", "🙂", 50),
    WARM("따뜻함", "🌡", 65)
}

data class ChatAnalysisResult(
    val id: Long = 0,
    val fileName: String,
    val periodStart: String,
    val periodEnd: String,
    val totalMessages: Int,
    val positiveRatio: Float,
    val neutralRatio: Float,
    val negativeRatio: Float,
    val temperature: Float,
    val temperatureLabel: String,
    val temperatureEmoji: String,
    val relationshipScore: Float,
    val topKeywords: List<String>,
    val autoDiaryDraft: String,
    val analyzedAt: Long
)

// ── Character ─────────────────────────────────────────────────────────────────
enum class CharacterType(
    val displayName: String,
    val emoji: String,
    val description: String,
    val recommendFor: String
) {
    CAT("솔이", "🐱", "고양이", "차분·집중형 | 루틴·집중력 향상이 목표인 분"),
    DOG("뭉치", "🐶", "강아지", "활동·사교형 | 건강과 운동이 목표인 분"),
    PLANT("새싹이", "🌱", "식물", "성장·치유형 | 마음 건강이 목표인 분"),
    FAIRY("루미", "✨", "요정", "감성·창의형 | 감정 일기와 자기표현이 목표인 분"),
    DRAGON("불꽃이", "🐉", "드래곤", "도전·목표형 | 높은 목표를 향해 달리는 분"),
    RABBIT("달토끼", "🐰", "달토끼", "꾸준함·평온형 | 습관 형성이 목표인 분")
}

data class CharacterState(
    val type: CharacterType,
    val name: String,
    val totalWp: Int,
    val level: Int,          // 1~5
    val levelName: String,   // 알/아기/성장/성숙/레전드
    val nextLevelWp: Int,
    val todayWp: Int
) {
    val progressRatio: Float get() {
        val prevWp = when (level) {
            1 -> 0; 2 -> 100; 3 -> 250; 4 -> 500; else -> 750
        }
        return if (nextLevelWp == prevWp) 1f
        else (totalWp - prevWp).toFloat() / (nextLevelWp - prevWp).toFloat()
    }
}

fun calculateCharacterLevel(totalWp: Int): Pair<Int, String> = when {
    totalWp < 100 -> 1 to "알"
    totalWp < 250 -> 2 to "아기"
    totalWp < 500 -> 3 to "성장"
    totalWp < 750 -> 4 to "성숙"
    else -> 5 to "레전드"
}

fun nextLevelWp(totalWp: Int): Int = when {
    totalWp < 100 -> 100
    totalWp < 250 -> 250
    totalWp < 500 -> 500
    totalWp < 750 -> 750
    else -> 1000
}

// ── Wellness Points ───────────────────────────────────────────────────────────
object WpEvent {
    const val ATTENDANCE = "ATTENDANCE"        // +5
    const val STREAK_7 = "STREAK_7"            // +10
    const val STREAK_30 = "STREAK_30"          // +30
    const val ROUTINE = "ROUTINE"              // +2 per routine (max +20/day)
    const val DIARY = "DIARY"                  // +3
    const val CHAT_ANALYSIS = "CHAT_ANALYSIS"  // +5

    fun points(event: String): Int = when (event) {
        ATTENDANCE -> 5
        STREAK_7 -> 10
        STREAK_30 -> 30
        ROUTINE -> 2
        DIARY -> 3
        CHAT_ANALYSIS -> 5
        else -> 0
    }
}
