package com.forlks.personal_wellness_routine.data.repository

import com.forlks.personal_wellness_routine.data.db.dao.DiaryDao
import com.forlks.personal_wellness_routine.data.db.entity.DiaryEntity
import com.forlks.personal_wellness_routine.domain.model.DiaryEntry
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class DiaryRepository @Inject constructor(
    private val diaryDao: DiaryDao
) {
    fun getAllDiaries(): Flow<List<DiaryEntry>> =
        diaryDao.getAllDiaries().map { list -> list.map { it.toDomain() } }

    suspend fun getDiaryForDate(date: String): DiaryEntry? =
        diaryDao.getDiaryForDate(date)?.toDomain()

    suspend fun saveDiary(entry: DiaryEntry): Long =
        diaryDao.insertDiary(entry.toEntity())

    suspend fun updateDiary(entry: DiaryEntry) =
        diaryDao.updateDiary(entry.toEntity())

    suspend fun deleteDiary(entry: DiaryEntry) =
        diaryDao.deleteDiary(entry.toEntity())

    suspend fun getAverageEmotionScore(startDate: String, endDate: String): Float =
        diaryDao.getAverageEmotionScore(startDate, endDate) ?: 0f

    private fun DiaryEntity.toDomain() = DiaryEntry(
        id = id, date = date, content = content,
        emotionEmoji = emotionEmoji, emotionScore = emotionScore,
        emotionLabel = emotionLabel,
        tags = if (tags.isBlank()) emptyList() else tags.split(","),
        isAutoGenerated = isAutoGenerated
    )

    private fun DiaryEntry.toEntity() = DiaryEntity(
        id = id, date = date, content = content,
        emotionEmoji = emotionEmoji, emotionScore = emotionScore,
        emotionLabel = emotionLabel,
        tags = tags.joinToString(","),
        isAutoGenerated = isAutoGenerated
    )
}
